"""initial schema

Revision ID: 35fbae838545
Revises: 
Create Date: 2026-09-15 08:20:54.793380

"""
from typing import Sequence, Union

from alembic import op
import pgvector
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '35fbae838545'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply the migration."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chunk_id', sa.String(length=512), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('doc_id', sa.String(length=500), nullable=False),
    sa.Column('relative_path', sa.String(length=500), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('doc_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chunks'))
    )
    with op.batch_alter_table('chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chunks_chunk_id'), ['chunk_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_chunks_doc_id'), ['doc_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chunks_relative_path'), ['relative_path'], unique=False)
        batch_op.create_index(batch_op.f('ix_chunks_run_id'), ['run_id'], unique=False)

    op.create_table('document_records',
    sa.Column('doc_id', sa.String(length=500), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('version_tag', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('access_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('classification', sa.String(length=32), nullable=False),
    sa.Column('department', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('relative_path', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('parent_directory', sa.String(length=500), nullable=False),
    sa.Column('file_extension', sa.String(length=16), nullable=False),
    sa.Column('mime_type', sa.String(length=64), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('checksum_algorithm', sa.String(length=16), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('modified_at', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('doc_id', name=op.f('pk_document_records'))
    )
    with op.batch_alter_table('document_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_records_relative_path'), ['relative_path'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_records_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('pipeline_runs',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('files_new', sa.Integer(), nullable=False),
    sa.Column('files_modified', sa.Integer(), nullable=False),
    sa.Column('files_deleted', sa.Integer(), nullable=False),
    sa.Column('files_unchanged', sa.Integer(), nullable=False),
    sa.Column('chunks_created', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('run_id', name=op.f('pk_pipeline_runs'))
    )
    op.create_table('run_events',
    sa.Column('event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_run_events'))
    )
    with op.batch_alter_table('run_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_events_run_id'), ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('run_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_events_run_id'))

    op.drop_table('run_events')
    op.drop_table('pipeline_runs')
    with op.batch_alter_table('document_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_records_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_document_records_relative_path'))

    op.drop_table('document_records')
    with op.batch_alter_table('chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chunks_run_id'))
        batch_op.drop_index(batch_op.f('ix_chunks_relative_path'))
        batch_op.drop_index(batch_op.f('ix_chunks_doc_id'))
        batch_op.drop_index(batch_op.f('ix_chunks_chunk_id'))

    op.drop_table('chunks')
    # ### end Alembic commands ###